version: '3'
services:
  search-api:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    command: npm run dev